# Generated by Django 4.2.21 on 2025-06-04 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interfacetestplatform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="模型名称")),
                ("test_owner", models.CharField(max_length=20, verbose_name="测试负责人")),
                (
                    "desc",
                    models.CharField(max_length=100, null=True, verbose_name="简要描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "belong_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interfacetestplatform.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型信息表",
                "verbose_name_plural": "模型信息表",
            },
        ),
    ]
