# Generated by Django 4.2.21 on 2025-06-05 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interfacetestplatform", "0003_test"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Test",
            new_name="TestCase",
        ),
        migrations.RenameField(
            model_name="testcase",
            old_name="belong_model",
            new_name="belong_module",
        ),
    ]
