# Generated by Django 4.2.21 on 2025-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interfacetestplatform", "0007_interfaceserver_alter_casesuite_if_execute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interfaceserver",
            name="ip",
            field=models.CharField(default="", max_length=50, verbose_name="ip"),
        ),
        migrations.AlterField(
            model_name="interfaceserver",
            name="port",
            field=models.CharField(default="", max_length=100, verbose_name="端口"),
        ),
    ]
