# Generated by Django 4.2.21 on 2025-06-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "interfacetestplatform",
            "0008_alter_interfaceserver_ip_alter_interfaceserver_port",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="interfaceserver",
            name="port",
            field=models.CharField(
                default="", max_length=100, null=True, verbose_name="端口"
            ),
        ),
    ]
