# Generated by Django 5.2.3 on 2025-06-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0010_testcaseexecuteresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='requests_header',
            field=models.TextField(null=True, verbose_name='请求头'),
        ),
    ]
